pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Tamer Dev App"
include(":app")

// GENERATED AUTOLINK START
// This section is automatically generated by Tamer4Lynx.
// Manual edits will be overwritten.
include(":tamer4lynx_tamer-dev-client")
project(":tamer4lynx_tamer-dev-client").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-dev-client/android")
include(":tamer4lynx_tamer-icons")
project(":tamer4lynx_tamer-icons").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-icons/android")
include(":tamer4lynx_tamer-insets")
project(":tamer4lynx_tamer-insets").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-insets/android")
include(":tamer4lynx_tamer-router")
project(":tamer4lynx_tamer-router").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-router/android")
include(":tamer4lynx_tamer-system-ui")
project(":tamer4lynx_tamer-system-ui").projectDir = file("/Volumes/Storage/Projects/tamer4lynx/node_modules/@tamer4lynx/tamer-system-ui/android")
include(":tamer4lynx_tamer-webview")
project(":tamer4lynx_tamer-webview").projectDir = file("../../tamer-webview/android")
// GENERATED AUTOLINK END
