pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Tamer Dev App"
include(":app")

// GENERATED AUTOLINK START
// This section is automatically generated by Tamer4Lynx.
// Manual edits will be overwritten.
include(":tamer4lynx_tamer-dev-client")
project(":tamer4lynx_tamer-dev-client").projectDir = file("/Volumes/Storage/Projects/e2ee/node_modules/@tamer4lynx/tamer-dev-app/node_modules/@tamer4lynx/tamer-dev-client/android")
// GENERATED AUTOLINK END
