pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Tamer Dev App"
include(":app")

// GENERATED AUTOLINK START
// This section is automatically generated by Tamer4Lynx.
// Manual edits will be overwritten.
include(":tamer-router")
project(":tamer-router").projectDir = file("../../../node_modules/tamer-router/android")
include(":tamer-text-input")
project(":tamer-text-input").projectDir = file("../../../node_modules/tamer-text-input/android")
include(":tamer-icons")
project(":tamer-icons").projectDir = file("../../../node_modules/tamer-icons/android")
include(":tamer-insets")
project(":tamer-insets").projectDir = file("../../../node_modules/tamer-insets/android")
include(":tamer-dev-client")
project(":tamer-dev-client").projectDir = file("../../../node_modules/tamer-dev-client/android")
include(":tamer-system-ui")
project(":tamer-system-ui").projectDir = file("../../../node_modules/tamer-system-ui/android")
include(":lynxwebsockets")
project(":lynxwebsockets").projectDir = file("../../../node_modules/lynxwebsockets/android")
include(":jiggle")
project(":jiggle").projectDir = file("../../../node_modules/jiggle/android")
// GENERATED AUTOLINK END
